# Generated by Django 4.0.6 on 2022-07-14 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=25)),
                ('genre', models.CharField(max_length=255)),
                ('play_time', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('casts', models.TextField()),
                ('synopsis', models.TextField()),
                ('avg_rating', models.FloatField(default=0)),
                ('number_rating', models.IntegerField(default=0)),
                ('cast_list', models.TextField()),
            ],
            options={
                'db_table': 'movie_lists',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_rating', models.IntegerField(default=0)),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movielist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'raitings',
            },
        ),
    ]
