# Generated by Django 4.0.6 on 2022-07-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movielist_casts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='poster',
            field=models.FileField(max_length=300, upload_to='poster/'),
        ),
    ]
