# Generated by Django 4.0.6 on 2022-07-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movielist_poster'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='ratings',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to='video/')),
                ('movie_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movielist')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
