# Generated by Django 4.0.6 on 2022-07-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_rating_table_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='movie_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='movies.movielist'),
        ),
    ]
